version: '3.3'

services:
  landing-service:
    build: ./landing
    hostname: landing-service
    ports:
      - 5051:5051
    networks:
      sample:
        aliases:
          - landing-service

  addition-service:
    build: ./addition
    hostname: addition-service
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - addition-service

  subtraction-service:
    build: ./subtraction
    hostname: subtraction-service
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - subtraction-service

  multiplication-service:
    build: ./multiplication
    hostname: multiplication-service
    ports:
      - 5054:5054
    networks:
      sample:
        aliases:
          - multiplication-service

  division-service:
    build: ./division
    hostname: division-service
    ports:
      - 5055:5055
    networks:
      sample:
        aliases:
          - division-service

networks:
  sample:
